server:
  port: 9000

spring:
  application:
    name: account-service

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

mgestiondeticket:
  cassandra:
    contact:
      point: 127.0.0.1
    port: 9042
    keyspace:
      name: springcloud
    username: cassandra
    password: cassandra