server:
  port: 9000

  boot:
    admin:
      client:
        url: localhost:8508

  management:
    endpoints:
      web:
        exposure:
          include: "*"

spring:
  application:
    name: account-service

  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

mgestiondeticket:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: springcloud
    username: cassandra
    password: cassandra