server:
  port: 9700

spring:
  application:
    name: kafka

logging:
  level:
    root: info

dedytech:
  kafka:
    address: 127.0.0.1:9092
    topic: dr-topic
    group:
      id: dr-group

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka