server:
  port: 9006

spring:
  application:
    name: notification-service

  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: localhost:8508

  rabbitmq:
    username: dedytech
    password: dedytech
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka
