server:
  port: 9005



spring:
  application:
    name: ticket-service

  zipkin:
    base-url: http://localhost:9411/

  datasource:
    url: jdbc:mysql://localhost:3306/microservicegestiondeticket
    username: root
    password: microservice-gestiondeticket

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

  rabbitmq:
    username: dedytech
    password: dedytech
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue


eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

