
version: '3.1'

networks:
  dedytech:

services:
  # DB and Queue -----------------------
  cassandra:
    image: cassandra
    container_name: dr-cassandra-server
    networks:
      - dedytech
    ports:
      - '9042:9042'

  mysql:
    image: mysql
    container_name: dr-mysql-server
    restart: always
    networks:
      - dedytech
    environment:
      MYSQL_ROOT_PASSWORD: microservice-app
    ports:
      - '3306:3306'

  elasticsearch:
    image: elasticsearch:6.8.5
    container_name: dr-elasticsearch
    networks:
      - dedytech
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node

  msrabbitmq:
    image: rabbitmq:3-management
    container_name: dr-msrabbitmq
    networks:
      - dedytech
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=dedytech
      - RABBITMQ_DEFAULT_PASS=dedytech

  # Local Services -----------------------

  dr-account-service:
    image: account-service:0.0.1-SNAPSHOT
    container_name: dr-account-service
    restart: always
    networks:
      - dedytech
    environment:
      CONFIG_SERVER_URL: http://dr-config-server:8888
      CASSANDRA_SERVER_HOST: dr-cassandra-server
    ports:
      - '8080:8080'

  dr-ticket-service:
    image: ticket-service:10.0.1
    container_name: dr-ticket-service
    restart: always
    networks:
      - dedytech
    environment:
      CONFIG_SERVER_URL: http://dr-config-server:8888
    ports:
      - '8080:8080'

  dr-notification-service:
    image: notification-service:10.0.1
    container_name: dr-notification-service
    restart: always
    networks:
      - dedytech
    environment:
      CONFIG_SERVER_URL: http://dr-config-server:8888
    ports:
      - '8080:8080'

  # System Services -----------------------
  dr-config-server:
    image: config-server:10.0.1
    container_name: dr-config-server
    restart: always
    networks:
      - dedytech
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      SERVER_PORT: 8888
    ports:
      - '8888:8888'

  dr-eureka-server:
    image: eureka-server:10.0.1
    container_name: dr-eureka-server
    restart: always
    networks:
      - dedytech
    environment:
      CONFIG_SERVER_URL: http://dr-config-server:8888
      SERVER_PORT: 8887
    ports:
      - '8887:8887'

  dr-admin-server:
    image: admin-server:10.0.1
    container_name: dr-admin-server
    restart: always
    networks:
      - dedytech
    environment:
      EUREKA_SERVICE_URL: http://dr-eureka-server:8888
      SERVER_PORT: 8886
    ports:
      - '8886:8886'

  dr-gateway-server:
    image: gateway-server:10.0.1
    container_name: dr-gateway-server
    restart: always
    networks:
      - dedytech
    environment:
      EUREKA_SERVICE_URL: http://dr-eureka-server:8888
      SERVER_PORT: 8885
    ports:
      - '8885:8885'

  dr-hystrix-dashboard:
    image: hystrix-dashboard:10.0.1
    container_name: dr-hystrix-dashboard
    restart: always
    networks:
      - dedytech
    environment:
      EUREKA_SERVICE_URL: http://dr-eureka-server:8888
      SERVER_PORT: 8884
    ports:
      - '8884:8884'

  dr-zipkin-server:
    image: zipkin-server:10.0.1
    container_name: dr-zipkin-server
    restart: always
    networks:
      - dedytech
    environment:
      EUREKA_SERVICE_URL: http://dr-eureka-server:8888
      SERVER_PORT: 8883
    ports:
      - '8883:8883'